default:
  image: debian:stable
pages:
  stage: deploy
  script:
    - wget https://github.com/badboy/mdbook-toc/releases/download/0.9.0/mdbook-toc-0.9.0-x86_64-unknown-linux-gnu.tar.gz
    - wget https://github.com/rust-lang/mdBook/releases/download/v0.4.18/mdbook-v0.4.18-x86_64-unknown-linux-gnu.tar.gz
    - tar xvzf mdbook-v0.4.18-x86_64-unknown-linux-gnu.tar.gz
    - tar xvzf mdbook-toc-0.9.0-x86_64-unknown-linux-gnu.tar.gz
    - export PATH=$PATH:./
    - mdbook build
  artifacts:
    paths:
      - public
  only:
    - main
