[book]
title = "moonsetOne Docs"
authors = ["rdlu"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "public"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
preferred-dark-theme = "navy"
default-theme = "rust"
google-analytics = "UA-163442290-1"