[book]
title = "CodeForLife Docs"
authors = ["rdlu"]
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "public"

[output.html]
preferred-dark-theme = "ayu"
default-theme = "ayu"
google-analytics = "UA-163442290-1"